/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.3
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface EmojiChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmojiChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 2;</code>
   * @return The user.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.User getUser();
  /**
   * <code>.User user = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>uint64 emojiId = 3;</code>
   * @return The emojiId.
   */
  long getEmojiId();

  /**
   * <code>.Text emojiContent = 4;</code>
   * @return Whether the emojiContent field is set.
   */
  boolean hasEmojiContent();
  /**
   * <code>.Text emojiContent = 4;</code>
   * @return The emojiContent.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.Text getEmojiContent();
  /**
   * <code>.Text emojiContent = 4;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.TextOrBuilder getEmojiContentOrBuilder();

  /**
   * <code>string defaultContent = 5;</code>
   * @return The defaultContent.
   */
  java.lang.String getDefaultContent();
  /**
   * <code>string defaultContent = 5;</code>
   * @return The bytes for defaultContent.
   */
  com.google.protobuf.ByteString
      getDefaultContentBytes();

  /**
   * <code>.Image backgroundImage = 6;</code>
   * @return Whether the backgroundImage field is set.
   */
  boolean hasBackgroundImage();
  /**
   * <code>.Image backgroundImage = 6;</code>
   * @return The backgroundImage.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.Image getBackgroundImage();
  /**
   * <code>.Image backgroundImage = 6;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.ImageOrBuilder getBackgroundImageOrBuilder();

  /**
   * <code>bool fromIntercom = 7;</code>
   * @return The fromIntercom.
   */
  boolean getFromIntercom();

  /**
   * <code>bool intercomHideUserCard = 8;</code>
   * @return The intercomHideUserCard.
   */
  boolean getIntercomHideUserCard();

  /**
   * <code>.PublicAreaCommon public_area_common = 9;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon public_area_common = 9;</code>
   * @return The publicAreaCommon.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.PublicAreaCommon public_area_common = 9;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();
}
