// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface GradeBuffInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GradeBuffInfo)
    com.google.protobuf.MessageOrBuilder {
}
