// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface GradeIconOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GradeIcon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Image icon = 1;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>.Image icon = 1;</code>
   * @return The icon.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.Image getIcon();
  /**
   * <code>.Image icon = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.ImageOrBuilder getIconOrBuilder();

  /**
   * <code>int64 iconDiamond = 2;</code>
   * @return The iconDiamond.
   */
  long getIconDiamond();

  /**
   * <code>int64 level = 3;</code>
   * @return The level.
   */
  long getLevel();

  /**
   * <code>string levelStr = 4;</code>
   * @return The levelStr.
   */
  java.lang.String getLevelStr();
  /**
   * <code>string levelStr = 4;</code>
   * @return The bytes for levelStr.
   */
  com.google.protobuf.ByteString
      getLevelStrBytes();
}
