/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.3
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface LikeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LikeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>uint64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>uint64 total = 3;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>uint64 color = 4;</code>
   * @return The color.
   */
  long getColor();

  /**
   * <code>.User user = 5;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 5;</code>
   * @return The user.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.User getUser();
  /**
   * <code>.User user = 5;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.UserOrBuilder getUserOrBuilder();

  /**
   * <code>string icon = 6;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>string icon = 6;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>.DoubleLikeDetail doubleLikeDetail = 7;</code>
   * @return Whether the doubleLikeDetail field is set.
   */
  boolean hasDoubleLikeDetail();
  /**
   * <code>.DoubleLikeDetail doubleLikeDetail = 7;</code>
   * @return The doubleLikeDetail.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.DoubleLikeDetail getDoubleLikeDetail();
  /**
   * <code>.DoubleLikeDetail doubleLikeDetail = 7;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.DoubleLikeDetailOrBuilder getDoubleLikeDetailOrBuilder();

  /**
   * <code>.DisplayControlInfo displayControlInfo = 8;</code>
   * @return Whether the displayControlInfo field is set.
   */
  boolean hasDisplayControlInfo();
  /**
   * <code>.DisplayControlInfo displayControlInfo = 8;</code>
   * @return The displayControlInfo.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.DisplayControlInfo getDisplayControlInfo();
  /**
   * <code>.DisplayControlInfo displayControlInfo = 8;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.DisplayControlInfoOrBuilder getDisplayControlInfoOrBuilder();

  /**
   * <code>uint64 linkmicGuestUid = 9;</code>
   * @return The linkmicGuestUid.
   */
  long getLinkmicGuestUid();

  /**
   * <code>string scene = 10;</code>
   * @return The scene.
   */
  java.lang.String getScene();
  /**
   * <code>string scene = 10;</code>
   * @return The bytes for scene.
   */
  com.google.protobuf.ByteString
      getSceneBytes();

  /**
   * <code>.PicoDisplayInfo picoDisplayInfo = 11;</code>
   * @return Whether the picoDisplayInfo field is set.
   */
  boolean hasPicoDisplayInfo();
  /**
   * <code>.PicoDisplayInfo picoDisplayInfo = 11;</code>
   * @return The picoDisplayInfo.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.PicoDisplayInfo getPicoDisplayInfo();
  /**
   * <code>.PicoDisplayInfo picoDisplayInfo = 11;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.PicoDisplayInfoOrBuilder getPicoDisplayInfoOrBuilder();
}
