/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.3
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface RanklistHourEntranceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RanklistHourEntrance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info global_infos = 1;</code>
   */
  java.util.List<tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info> 
      getGlobalInfosList();
  /**
   * <pre>
   * 全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info global_infos = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info getGlobalInfos(int index);
  /**
   * <pre>
   * 全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info global_infos = 1;</code>
   */
  int getGlobalInfosCount();
  /**
   * <pre>
   * 全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info global_infos = 1;</code>
   */
  java.util.List<? extends tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder> 
      getGlobalInfosOrBuilderList();
  /**
   * <pre>
   * 全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info global_infos = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder getGlobalInfosOrBuilder(
      int index);

  /**
   * <pre>
   * 默认全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_global_infos = 2;</code>
   */
  java.util.List<tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info> 
      getDefaultGlobalInfosList();
  /**
   * <pre>
   * 默认全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_global_infos = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info getDefaultGlobalInfos(int index);
  /**
   * <pre>
   * 默认全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_global_infos = 2;</code>
   */
  int getDefaultGlobalInfosCount();
  /**
   * <pre>
   * 默认全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_global_infos = 2;</code>
   */
  java.util.List<? extends tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder> 
      getDefaultGlobalInfosOrBuilderList();
  /**
   * <pre>
   * 默认全局信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_global_infos = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder getDefaultGlobalInfosOrBuilder(
      int index);

  /**
   * <pre>
   * 垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info vertical_infos = 3;</code>
   */
  java.util.List<tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info> 
      getVerticalInfosList();
  /**
   * <pre>
   * 垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info vertical_infos = 3;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info getVerticalInfos(int index);
  /**
   * <pre>
   * 垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info vertical_infos = 3;</code>
   */
  int getVerticalInfosCount();
  /**
   * <pre>
   * 垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info vertical_infos = 3;</code>
   */
  java.util.List<? extends tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder> 
      getVerticalInfosOrBuilderList();
  /**
   * <pre>
   * 垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info vertical_infos = 3;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder getVerticalInfosOrBuilder(
      int index);

  /**
   * <pre>
   * 默认垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_vertical_infos = 4;</code>
   */
  java.util.List<tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info> 
      getDefaultVerticalInfosList();
  /**
   * <pre>
   * 默认垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_vertical_infos = 4;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_Info getDefaultVerticalInfos(int index);
  /**
   * <pre>
   * 默认垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_vertical_infos = 4;</code>
   */
  int getDefaultVerticalInfosCount();
  /**
   * <pre>
   * 默认垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_vertical_infos = 4;</code>
   */
  java.util.List<? extends tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder> 
      getDefaultVerticalInfosOrBuilderList();
  /**
   * <pre>
   * 默认垂直信息列表
   * </pre>
   *
   * <code>repeated .RanklistHourEntrance_Info default_vertical_infos = 4;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance_InfoOrBuilder getDefaultVerticalInfosOrBuilder(
      int index);
}
