// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface RanklistHourEntranceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RanklistHourEntranceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.Common common = 1;</code>
   * @return The common.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.Common getCommon();
  /**
   * <code>.Common common = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.RanklistHourEntrance info = 2;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.RanklistHourEntrance info = 2;</code>
   * @return The info.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntrance getInfo();
  /**
   * <code>.RanklistHourEntrance info = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.RanklistHourEntranceOrBuilder getInfoOrBuilder();
}
