// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface TextEffectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextEffect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TextEffectDetail portrait = 1;</code>
   * @return Whether the portrait field is set.
   */
  boolean hasPortrait();
  /**
   * <code>.TextEffectDetail portrait = 1;</code>
   * @return The portrait.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.TextEffectDetail getPortrait();
  /**
   * <code>.TextEffectDetail portrait = 1;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.TextEffectDetailOrBuilder getPortraitOrBuilder();

  /**
   * <code>.TextEffectDetail landscape = 2;</code>
   * @return Whether the landscape field is set.
   */
  boolean hasLandscape();
  /**
   * <code>.TextEffectDetail landscape = 2;</code>
   * @return The landscape.
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.TextEffectDetail getLandscape();
  /**
   * <code>.TextEffectDetail landscape = 2;</code>
   */
  tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.TextEffectDetailOrBuilder getLandscapeOrBuilder();
}
