/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.3
package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf;

public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string default_pattern = 2;</code>
   * @return The defaultPattern.
   */
  String getDefaultPattern();
  /**
   * <code>string default_pattern = 2;</code>
   * @return The bytes for defaultPattern.
   */
  com.google.protobuf.ByteString
      getDefaultPatternBytes();

  /**
   * <code>.TextFormat default_format = 3;</code>
   * @return Whether the defaultFormat field is set.
   */
  boolean hasDefaultFormat();
  /**
   * <code>.TextFormat default_format = 3;</code>
   * @return The defaultFormat.
   */
  TextFormat getDefaultFormat();
  /**
   * <code>.TextFormat default_format = 3;</code>
   */
  TextFormatOrBuilder getDefaultFormatOrBuilder();

  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  java.util.List<TextPiece>
      getPiecesList();
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  TextPiece getPieces(int index);
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  int getPiecesCount();
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  java.util.List<? extends TextPieceOrBuilder>
      getPiecesOrBuilderList();
  /**
   * <code>repeated .TextPiece pieces = 4;</code>
   */
  TextPieceOrBuilder getPiecesOrBuilder(
      int index);
}
