/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Text.proto

package tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.dto;

public final class TextOuterClass {
  private TextOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Text)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string default_patter = 2;</code>
     * @return The defaultPatter.
     */
    String getDefaultPatter();
    /**
     * <code>string default_patter = 2;</code>
     * @return The bytes for defaultPatter.
     */
    com.google.protobuf.ByteString
        getDefaultPatterBytes();

    /**
     * <code>.TextFormat default_format = 3;</code>
     * @return Whether the defaultFormat field is set.
     */
    boolean hasDefaultFormat();
    /**
     * <code>.TextFormat default_format = 3;</code>
     * @return The defaultFormat.
     */
    TextFormatOuterClass.TextFormat getDefaultFormat();
    /**
     * <code>.TextFormat default_format = 3;</code>
     */
    TextFormatOuterClass.TextFormatOrBuilder getDefaultFormatOrBuilder();

    /**
     * <code>.TextPiece pieces_list = 4;</code>
     * @return Whether the piecesList field is set.
     */
    boolean hasPiecesList();
    /**
     * <code>.TextPiece pieces_list = 4;</code>
     * @return The piecesList.
     */
    TextPieceOuterClass.TextPiece getPiecesList();
    /**
     * <code>.TextPiece pieces_list = 4;</code>
     */
    TextPieceOuterClass.TextPieceOrBuilder getPiecesListOrBuilder();
  }
  /**
   * Protobuf type {@code Text}
   */
  public static final class Text extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Text)
      TextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Text.newBuilder() to construct.
    private Text(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Text() {
      key_ = "";
      defaultPatter_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Text();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextOuterClass.internal_static_Text_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextOuterClass.internal_static_Text_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Text.class, Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @Override
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULT_PATTER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object defaultPatter_ = "";
    /**
     * <code>string default_patter = 2;</code>
     * @return The defaultPatter.
     */
    @Override
    public String getDefaultPatter() {
      Object ref = defaultPatter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        defaultPatter_ = s;
        return s;
      }
    }
    /**
     * <code>string default_patter = 2;</code>
     * @return The bytes for defaultPatter.
     */
    @Override
    public com.google.protobuf.ByteString
        getDefaultPatterBytes() {
      Object ref = defaultPatter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        defaultPatter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULT_FORMAT_FIELD_NUMBER = 3;
    private TextFormatOuterClass.TextFormat defaultFormat_;
    /**
     * <code>.TextFormat default_format = 3;</code>
     * @return Whether the defaultFormat field is set.
     */
    @Override
    public boolean hasDefaultFormat() {
      return defaultFormat_ != null;
    }
    /**
     * <code>.TextFormat default_format = 3;</code>
     * @return The defaultFormat.
     */
    @Override
    public TextFormatOuterClass.TextFormat getDefaultFormat() {
      return defaultFormat_ == null ? TextFormatOuterClass.TextFormat.getDefaultInstance() : defaultFormat_;
    }
    /**
     * <code>.TextFormat default_format = 3;</code>
     */
    @Override
    public TextFormatOuterClass.TextFormatOrBuilder getDefaultFormatOrBuilder() {
      return defaultFormat_ == null ? TextFormatOuterClass.TextFormat.getDefaultInstance() : defaultFormat_;
    }

    public static final int PIECES_LIST_FIELD_NUMBER = 4;
    private TextPieceOuterClass.TextPiece piecesList_;
    /**
     * <code>.TextPiece pieces_list = 4;</code>
     * @return Whether the piecesList field is set.
     */
    @Override
    public boolean hasPiecesList() {
      return piecesList_ != null;
    }
    /**
     * <code>.TextPiece pieces_list = 4;</code>
     * @return The piecesList.
     */
    @Override
    public TextPieceOuterClass.TextPiece getPiecesList() {
      return piecesList_ == null ? TextPieceOuterClass.TextPiece.getDefaultInstance() : piecesList_;
    }
    /**
     * <code>.TextPiece pieces_list = 4;</code>
     */
    @Override
    public TextPieceOuterClass.TextPieceOrBuilder getPiecesListOrBuilder() {
      return piecesList_ == null ? TextPieceOuterClass.TextPiece.getDefaultInstance() : piecesList_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(defaultPatter_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, defaultPatter_);
      }
      if (defaultFormat_ != null) {
        output.writeMessage(3, getDefaultFormat());
      }
      if (piecesList_ != null) {
        output.writeMessage(4, getPiecesList());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(defaultPatter_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, defaultPatter_);
      }
      if (defaultFormat_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDefaultFormat());
      }
      if (piecesList_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPiecesList());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Text)) {
        return super.equals(obj);
      }
      Text other = (Text) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getDefaultPatter()
          .equals(other.getDefaultPatter())) return false;
      if (hasDefaultFormat() != other.hasDefaultFormat()) return false;
      if (hasDefaultFormat()) {
        if (!getDefaultFormat()
            .equals(other.getDefaultFormat())) return false;
      }
      if (hasPiecesList() != other.hasPiecesList()) return false;
      if (hasPiecesList()) {
        if (!getPiecesList()
            .equals(other.getPiecesList())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + DEFAULT_PATTER_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultPatter().hashCode();
      if (hasDefaultFormat()) {
        hash = (37 * hash) + DEFAULT_FORMAT_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultFormat().hashCode();
      }
      if (hasPiecesList()) {
        hash = (37 * hash) + PIECES_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getPiecesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Text parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Text parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Text parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Text parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Text parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Text parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Text parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Text parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Text parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Text parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Text parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Text parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Text prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Text}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Text)
        TextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextOuterClass.internal_static_Text_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextOuterClass.internal_static_Text_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Text.class, Builder.class);
      }

      // Construct using tech.ordinaryroad.live.chat.client.codec.douyin.protobuf.dto.TextOuterClass.Text.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        defaultPatter_ = "";
        defaultFormat_ = null;
        if (defaultFormatBuilder_ != null) {
          defaultFormatBuilder_.dispose();
          defaultFormatBuilder_ = null;
        }
        piecesList_ = null;
        if (piecesListBuilder_ != null) {
          piecesListBuilder_.dispose();
          piecesListBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextOuterClass.internal_static_Text_descriptor;
      }

      @Override
      public Text getDefaultInstanceForType() {
        return Text.getDefaultInstance();
      }

      @Override
      public Text build() {
        Text result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Text buildPartial() {
        Text result = new Text(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Text result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.defaultPatter_ = defaultPatter_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.defaultFormat_ = defaultFormatBuilder_ == null
              ? defaultFormat_
              : defaultFormatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.piecesList_ = piecesListBuilder_ == null
              ? piecesList_
              : piecesListBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Text) {
          return mergeFrom((Text)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Text other) {
        if (other == Text.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDefaultPatter().isEmpty()) {
          defaultPatter_ = other.defaultPatter_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasDefaultFormat()) {
          mergeDefaultFormat(other.getDefaultFormat());
        }
        if (other.hasPiecesList()) {
          mergePiecesList(other.getPiecesList());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                defaultPatter_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getDefaultFormatFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getPiecesListFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object defaultPatter_ = "";
      /**
       * <code>string default_patter = 2;</code>
       * @return The defaultPatter.
       */
      public String getDefaultPatter() {
        Object ref = defaultPatter_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          defaultPatter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string default_patter = 2;</code>
       * @return The bytes for defaultPatter.
       */
      public com.google.protobuf.ByteString
          getDefaultPatterBytes() {
        Object ref = defaultPatter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          defaultPatter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string default_patter = 2;</code>
       * @param value The defaultPatter to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultPatter(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        defaultPatter_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string default_patter = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultPatter() {
        defaultPatter_ = getDefaultInstance().getDefaultPatter();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string default_patter = 2;</code>
       * @param value The bytes for defaultPatter to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultPatterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        defaultPatter_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private TextFormatOuterClass.TextFormat defaultFormat_;
      private com.google.protobuf.SingleFieldBuilderV3<
          TextFormatOuterClass.TextFormat, TextFormatOuterClass.TextFormat.Builder, TextFormatOuterClass.TextFormatOrBuilder> defaultFormatBuilder_;
      /**
       * <code>.TextFormat default_format = 3;</code>
       * @return Whether the defaultFormat field is set.
       */
      public boolean hasDefaultFormat() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       * @return The defaultFormat.
       */
      public TextFormatOuterClass.TextFormat getDefaultFormat() {
        if (defaultFormatBuilder_ == null) {
          return defaultFormat_ == null ? TextFormatOuterClass.TextFormat.getDefaultInstance() : defaultFormat_;
        } else {
          return defaultFormatBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      public Builder setDefaultFormat(TextFormatOuterClass.TextFormat value) {
        if (defaultFormatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          defaultFormat_ = value;
        } else {
          defaultFormatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      public Builder setDefaultFormat(
          TextFormatOuterClass.TextFormat.Builder builderForValue) {
        if (defaultFormatBuilder_ == null) {
          defaultFormat_ = builderForValue.build();
        } else {
          defaultFormatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      public Builder mergeDefaultFormat(TextFormatOuterClass.TextFormat value) {
        if (defaultFormatBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            defaultFormat_ != null &&
            defaultFormat_ != TextFormatOuterClass.TextFormat.getDefaultInstance()) {
            getDefaultFormatBuilder().mergeFrom(value);
          } else {
            defaultFormat_ = value;
          }
        } else {
          defaultFormatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      public Builder clearDefaultFormat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        defaultFormat_ = null;
        if (defaultFormatBuilder_ != null) {
          defaultFormatBuilder_.dispose();
          defaultFormatBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      public TextFormatOuterClass.TextFormat.Builder getDefaultFormatBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDefaultFormatFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      public TextFormatOuterClass.TextFormatOrBuilder getDefaultFormatOrBuilder() {
        if (defaultFormatBuilder_ != null) {
          return defaultFormatBuilder_.getMessageOrBuilder();
        } else {
          return defaultFormat_ == null ?
              TextFormatOuterClass.TextFormat.getDefaultInstance() : defaultFormat_;
        }
      }
      /**
       * <code>.TextFormat default_format = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TextFormatOuterClass.TextFormat, TextFormatOuterClass.TextFormat.Builder, TextFormatOuterClass.TextFormatOrBuilder>
          getDefaultFormatFieldBuilder() {
        if (defaultFormatBuilder_ == null) {
          defaultFormatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TextFormatOuterClass.TextFormat, TextFormatOuterClass.TextFormat.Builder, TextFormatOuterClass.TextFormatOrBuilder>(
                  getDefaultFormat(),
                  getParentForChildren(),
                  isClean());
          defaultFormat_ = null;
        }
        return defaultFormatBuilder_;
      }

      private TextPieceOuterClass.TextPiece piecesList_;
      private com.google.protobuf.SingleFieldBuilderV3<
          TextPieceOuterClass.TextPiece, TextPieceOuterClass.TextPiece.Builder, TextPieceOuterClass.TextPieceOrBuilder> piecesListBuilder_;
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       * @return Whether the piecesList field is set.
       */
      public boolean hasPiecesList() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       * @return The piecesList.
       */
      public TextPieceOuterClass.TextPiece getPiecesList() {
        if (piecesListBuilder_ == null) {
          return piecesList_ == null ? TextPieceOuterClass.TextPiece.getDefaultInstance() : piecesList_;
        } else {
          return piecesListBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      public Builder setPiecesList(TextPieceOuterClass.TextPiece value) {
        if (piecesListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          piecesList_ = value;
        } else {
          piecesListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      public Builder setPiecesList(
          TextPieceOuterClass.TextPiece.Builder builderForValue) {
        if (piecesListBuilder_ == null) {
          piecesList_ = builderForValue.build();
        } else {
          piecesListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      public Builder mergePiecesList(TextPieceOuterClass.TextPiece value) {
        if (piecesListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            piecesList_ != null &&
            piecesList_ != TextPieceOuterClass.TextPiece.getDefaultInstance()) {
            getPiecesListBuilder().mergeFrom(value);
          } else {
            piecesList_ = value;
          }
        } else {
          piecesListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      public Builder clearPiecesList() {
        bitField0_ = (bitField0_ & ~0x00000008);
        piecesList_ = null;
        if (piecesListBuilder_ != null) {
          piecesListBuilder_.dispose();
          piecesListBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      public TextPieceOuterClass.TextPiece.Builder getPiecesListBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPiecesListFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      public TextPieceOuterClass.TextPieceOrBuilder getPiecesListOrBuilder() {
        if (piecesListBuilder_ != null) {
          return piecesListBuilder_.getMessageOrBuilder();
        } else {
          return piecesList_ == null ?
              TextPieceOuterClass.TextPiece.getDefaultInstance() : piecesList_;
        }
      }
      /**
       * <code>.TextPiece pieces_list = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TextPieceOuterClass.TextPiece, TextPieceOuterClass.TextPiece.Builder, TextPieceOuterClass.TextPieceOrBuilder>
          getPiecesListFieldBuilder() {
        if (piecesListBuilder_ == null) {
          piecesListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TextPieceOuterClass.TextPiece, TextPieceOuterClass.TextPiece.Builder, TextPieceOuterClass.TextPieceOrBuilder>(
                  getPiecesList(),
                  getParentForChildren(),
                  isClean());
          piecesList_ = null;
        }
        return piecesListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Text)
    }

    // @@protoc_insertion_point(class_scope:Text)
    private static final Text DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Text();
    }

    public static Text getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Text>
        PARSER = new com.google.protobuf.AbstractParser<Text>() {
      @Override
      public Text parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Text> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Text> getParserForType() {
      return PARSER;
    }

    @Override
    public Text getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Text_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Text_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nText.proto\032\020TextFormat.proto\032\017TextPiec" +
      "e.proto\"q\n\004Text\022\013\n\003key\030\001 \001(\t\022\026\n\016default_" +
      "patter\030\002 \001(\t\022#\n\016default_format\030\003 \001(\0132\013.T" +
      "extFormat\022\037\n\013pieces_list\030\004 \001(\0132\n.TextPie" +
      "ceB>\n<tech.ordinaryroad.live.chat.client" +
      ".codec.douyin.protobuf.dtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TextFormatOuterClass.getDescriptor(),
          TextPieceOuterClass.getDescriptor(),
        });
    internal_static_Text_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Text_descriptor,
        new String[] { "Key", "DefaultPatter", "DefaultFormat", "PiecesList", });
    TextFormatOuterClass.getDescriptor();
    TextPieceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
