/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kuaishou_websocket_danmu_frame.proto

package tech.ordinaryroad.live.chat.client.kuaishou.protobuf;

/**
 * Protobuf type {@code tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5}
 */
public final class DanmuMsg_5 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5)
    DanmuMsg_5OrBuilder {
private static final long serialVersionUID = 0L;
  // Use DanmuMsg_5.newBuilder() to construct.
  private DanmuMsg_5(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DanmuMsg_5() {
    content_ = "";
    string4_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DanmuMsg_5();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.kuaishou_websocket_danmu_msgProto.internal_static_tech_ordinaryroad_live_chat_client_kuaishou_protobuf_DanmuMsg_5_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.kuaishou_websocket_danmu_msgProto.internal_static_tech_ordinaryroad_live_chat_client_kuaishou_protobuf_DanmuMsg_5_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.class, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.Builder.class);
  }

  public static final int DANMUMSG_5_2_FIELD_NUMBER = 2;
  private tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg52_;
  /**
   * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
   * @return Whether the danmuMsg52 field is set.
   */
  @java.lang.Override
  public boolean hasDanmuMsg52() {
    return danmuMsg52_ != null;
  }
  /**
   * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
   * @return The danmuMsg52.
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 getDanmuMsg52() {
    return danmuMsg52_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.getDefaultInstance() : danmuMsg52_;
  }
  /**
   * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
   */
  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2OrBuilder getDanmuMsg52OrBuilder() {
    return danmuMsg52_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.getDefaultInstance() : danmuMsg52_;
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRING_4_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object string4_ = "";
  /**
   * <pre>
   * uint64 int_7 = 7;
   * </pre>
   *
   * <code>string string_4 = 4;</code>
   * @return The string4.
   */
  @java.lang.Override
  public java.lang.String getString4() {
    java.lang.Object ref = string4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      string4_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * uint64 int_7 = 7;
   * </pre>
   *
   * <code>string string_4 = 4;</code>
   * @return The bytes for string4.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getString4Bytes() {
    java.lang.Object ref = string4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      string4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (danmuMsg52_ != null) {
      output.writeMessage(2, getDanmuMsg52());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string4_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, string4_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (danmuMsg52_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDanmuMsg52());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string4_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, string4_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5)) {
      return super.equals(obj);
    }
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 other = (tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5) obj;

    if (hasDanmuMsg52() != other.hasDanmuMsg52()) return false;
    if (hasDanmuMsg52()) {
      if (!getDanmuMsg52()
          .equals(other.getDanmuMsg52())) return false;
    }
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getString4()
        .equals(other.getString4())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDanmuMsg52()) {
      hash = (37 * hash) + DANMUMSG_5_2_FIELD_NUMBER;
      hash = (53 * hash) + getDanmuMsg52().hashCode();
    }
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + STRING_4_FIELD_NUMBER;
    hash = (53 * hash) + getString4().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5)
      tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.kuaishou_websocket_danmu_msgProto.internal_static_tech_ordinaryroad_live_chat_client_kuaishou_protobuf_DanmuMsg_5_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.kuaishou_websocket_danmu_msgProto.internal_static_tech_ordinaryroad_live_chat_client_kuaishou_protobuf_DanmuMsg_5_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.class, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.Builder.class);
    }

    // Construct using tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      danmuMsg52_ = null;
      if (danmuMsg52Builder_ != null) {
        danmuMsg52Builder_.dispose();
        danmuMsg52Builder_ = null;
      }
      content_ = "";
      string4_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.kuaishou_websocket_danmu_msgProto.internal_static_tech_ordinaryroad_live_chat_client_kuaishou_protobuf_DanmuMsg_5_descriptor;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 getDefaultInstanceForType() {
      return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.getDefaultInstance();
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 build() {
      tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 buildPartial() {
      tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 result = new tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.danmuMsg52_ = danmuMsg52Builder_ == null
            ? danmuMsg52_
            : danmuMsg52Builder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.string4_ = string4_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5) {
        return mergeFrom((tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 other) {
      if (other == tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5.getDefaultInstance()) return this;
      if (other.hasDanmuMsg52()) {
        mergeDanmuMsg52(other.getDanmuMsg52());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getString4().isEmpty()) {
        string4_ = other.string4_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              input.readMessage(
                  getDanmuMsg52FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 18
            case 26: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            case 34: {
              string4_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg52_;
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2OrBuilder> danmuMsg52Builder_;
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     * @return Whether the danmuMsg52 field is set.
     */
    public boolean hasDanmuMsg52() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     * @return The danmuMsg52.
     */
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 getDanmuMsg52() {
      if (danmuMsg52Builder_ == null) {
        return danmuMsg52_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.getDefaultInstance() : danmuMsg52_;
      } else {
        return danmuMsg52Builder_.getMessage();
      }
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    public Builder setDanmuMsg52(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 value) {
      if (danmuMsg52Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        danmuMsg52_ = value;
      } else {
        danmuMsg52Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    public Builder setDanmuMsg52(
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.Builder builderForValue) {
      if (danmuMsg52Builder_ == null) {
        danmuMsg52_ = builderForValue.build();
      } else {
        danmuMsg52Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    public Builder mergeDanmuMsg52(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 value) {
      if (danmuMsg52Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          danmuMsg52_ != null &&
          danmuMsg52_ != tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.getDefaultInstance()) {
          getDanmuMsg52Builder().mergeFrom(value);
        } else {
          danmuMsg52_ = value;
        }
      } else {
        danmuMsg52Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    public Builder clearDanmuMsg52() {
      bitField0_ = (bitField0_ & ~0x00000001);
      danmuMsg52_ = null;
      if (danmuMsg52Builder_ != null) {
        danmuMsg52Builder_.dispose();
        danmuMsg52Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.Builder getDanmuMsg52Builder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDanmuMsg52FieldBuilder().getBuilder();
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2OrBuilder getDanmuMsg52OrBuilder() {
      if (danmuMsg52Builder_ != null) {
        return danmuMsg52Builder_.getMessageOrBuilder();
      } else {
        return danmuMsg52_ == null ?
            tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.getDefaultInstance() : danmuMsg52_;
      }
    }
    /**
     * <code>.tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2 danmuMsg_5_2 = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2OrBuilder> 
        getDanmuMsg52FieldBuilder() {
      if (danmuMsg52Builder_ == null) {
        danmuMsg52Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5_2OrBuilder>(
                getDanmuMsg52(),
                getParentForChildren(),
                isClean());
        danmuMsg52_ = null;
      }
      return danmuMsg52Builder_;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object string4_ = "";
    /**
     * <pre>
     * uint64 int_7 = 7;
     * </pre>
     *
     * <code>string string_4 = 4;</code>
     * @return The string4.
     */
    public java.lang.String getString4() {
      java.lang.Object ref = string4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * uint64 int_7 = 7;
     * </pre>
     *
     * <code>string string_4 = 4;</code>
     * @return The bytes for string4.
     */
    public com.google.protobuf.ByteString
        getString4Bytes() {
      java.lang.Object ref = string4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * uint64 int_7 = 7;
     * </pre>
     *
     * <code>string string_4 = 4;</code>
     * @param value The string4 to set.
     * @return This builder for chaining.
     */
    public Builder setString4(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      string4_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uint64 int_7 = 7;
     * </pre>
     *
     * <code>string string_4 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearString4() {
      string4_ = getDefaultInstance().getString4();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uint64 int_7 = 7;
     * </pre>
     *
     * <code>string string_4 = 4;</code>
     * @param value The bytes for string4 to set.
     * @return This builder for chaining.
     */
    public Builder setString4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      string4_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5)
  }

  // @@protoc_insertion_point(class_scope:tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5)
  private static final tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5();
  }

  public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DanmuMsg_5>
      PARSER = new com.google.protobuf.AbstractParser<DanmuMsg_5>() {
    @java.lang.Override
    public DanmuMsg_5 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DanmuMsg_5> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DanmuMsg_5> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.DanmuMsg_5 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

