/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InteractiveChatRoomInfo.proto

// Protobuf Java Version: 3.25.5
package tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf;

public final class InteractiveChatRoomInfoOuterClass {
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InteractiveChatRoomInfo_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InteractiveChatRoomInfo_fieldAccessorTable;
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\035InteractiveChatRoomInfo.proto\"?\n\027Inter" +
      "activeChatRoomInfo\022\023\n\013bizIdentity\030\001 \001(\004\022" +
      "\017\n\007version\030\004 \001(\004B<\n:tech.ordinaryroad.li" +
      "ve.chat.client.codec.kuaishou.protobufb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InteractiveChatRoomInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InteractiveChatRoomInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InteractiveChatRoomInfo_descriptor,
        new java.lang.String[] { "BizIdentity", "Version", });
  }
  private InteractiveChatRoomInfoOuterClass() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  public interface InteractiveChatRoomInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InteractiveChatRoomInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 bizIdentity = 1;</code>
     * @return The bizIdentity.
     */
    long getBizIdentity();

    /**
     * <code>uint64 version = 4;</code>
     * @return The version.
     */
    long getVersion();
  }

  /**
   * Protobuf type {@code InteractiveChatRoomInfo}
   */
  public static final class InteractiveChatRoomInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InteractiveChatRoomInfo)
      InteractiveChatRoomInfoOrBuilder {
    public static final int BIZIDENTITY_FIELD_NUMBER = 1;
    public static final int VERSION_FIELD_NUMBER = 4;
  private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:InteractiveChatRoomInfo)
    private static final tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<InteractiveChatRoomInfo>
        PARSER = new com.google.protobuf.AbstractParser<InteractiveChatRoomInfo>() {
      @java.lang.Override
      public InteractiveChatRoomInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    static {
      DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo();
    }

    private long bizIdentity_ = 0L;
    private long version_ = 0L;
    private byte memoizedIsInitialized = -1;

    // Use InteractiveChatRoomInfo.newBuilder() to construct.
    private InteractiveChatRoomInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InteractiveChatRoomInfo() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.internal_static_InteractiveChatRoomInfo_descriptor;
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<InteractiveChatRoomInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InteractiveChatRoomInfo();
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.internal_static_InteractiveChatRoomInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.class, tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.Builder.class);
    }

    /**
     * <code>uint64 bizIdentity = 1;</code>
     * @return The bizIdentity.
     */
    @java.lang.Override
    public long getBizIdentity() {
      return bizIdentity_;
    }

    /**
     * <code>uint64 version = 4;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bizIdentity_ != 0L) {
        output.writeUInt64(1, bizIdentity_);
      }
      if (version_ != 0L) {
        output.writeUInt64(4, version_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bizIdentity_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, bizIdentity_);
      }
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo)) {
        return super.equals(obj);
      }
      tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo other = (tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo) obj;

      if (getBizIdentity()
          != other.getBizIdentity()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BIZIDENTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBizIdentity());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InteractiveChatRoomInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code InteractiveChatRoomInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InteractiveChatRoomInfo)
        tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfoOrBuilder {
      private int bitField0_;
      private long bizIdentity_ ;
      private long version_ ;

      // Construct using tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.newBuilder()
      private Builder() {

      }
      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.internal_static_InteractiveChatRoomInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.internal_static_InteractiveChatRoomInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.class, tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.Builder.class);
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bizIdentity_ = 0L;
        version_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.internal_static_InteractiveChatRoomInfo_descriptor;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo getDefaultInstanceForType() {
        return tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.getDefaultInstance();
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo build() {
        tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo buildPartial() {
        tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo result = new tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bizIdentity_ = bizIdentity_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo) {
          return mergeFrom((tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo other) {
        if (other == tech.ordinaryroad.live.chat.client.codec.kuaishou.protobuf.InteractiveChatRoomInfoOuterClass.InteractiveChatRoomInfo.getDefaultInstance()) return this;
        if (other.getBizIdentity() != 0L) {
          setBizIdentity(other.getBizIdentity());
        }
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bizIdentity_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 32: {
                version_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      /**
       * <code>uint64 bizIdentity = 1;</code>
       * @return The bizIdentity.
       */
      @java.lang.Override
      public long getBizIdentity() {
        return bizIdentity_;
      }

      /**
       * <code>uint64 bizIdentity = 1;</code>
       * @param value The bizIdentity to set.
       * @return This builder for chaining.
       */
      public Builder setBizIdentity(long value) {

        bizIdentity_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 bizIdentity = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBizIdentity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bizIdentity_ = 0L;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 version = 4;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <code>uint64 version = 4;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InteractiveChatRoomInfo)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
